service: quizito-backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 
  vpc: [] 

package:
  patterns:
    - '!./**'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'
    - '.env'

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
